### ISSUE TITLE
New preset: The Hacienda

### ISSUE THREAD

**Issue by thomasageorge333** [nzoschke/vizlab-presets#14]
{
  "hate": [],
  "love": [
    "/Dancer/Blobby_Mirror/LuxXx-BadBallz",
    "/Dancer/Blobby_Mirror/LuxXx-Dancing_Or_Mating_Blobs_II",
    "/Dancer/Blobby_Mirror/ORB-Radiation",
    "/Dancer/Blobby/suksma-dog_vs_hog_vs_chicken",
    "/Dancer/Glowsticks/Tripgnosis-Firesticks-Isosceles_edit01",
    "/Dancer/Blobby_Mirror/ORB-Radiation2",
    "/Dancer/Blobby_Mirror/suksma-dog_vs_hog_vs_chicken-naughty_little_people",
    "/Dancer/Glowsticks/Royal-Mashup_17_",
    "/Dancer/Glowsticks/293",
    "/Dancer/Glowsticks_Mirror/Hexcollie-Demonic_Afterimages",
    "/Dancer/Glowsticks_Mirror/EoS_+_Redi_Jedi-frequency_analysis_+_glowsticks-long_armed_raver_Milkdrop_beta_ver_",
    "/Dancer/Glowsticks_Mirror/142_nz",
    "/Dancer/Glowsticks_Mirror/shifter-rececho",
    "/Dancer/Petals/suksma-opsolete_fraqthal_dihmention_o_cloque",
    "/Geometric/Wire_Morph/EoS_Phat_craZy",
    "/Fractal/Nested_Triangle/PieturP-HSL-here-we-go-circle",
    "/Drawing/Lasers/235",
    "/Drawing/Lasers/suksma-probate_judge_spawn_beast",
    "/Sparkle/Squares/Zylot-DISCO_INFERNO_solid_floor_Epileptic_Boogaloo_Jelly_",
    "/Waveform/Wire_Circular/Aderrasi-Chromatic_Abyss_Refined_Abyss_Mix_",
    "/Waveform/Wire_Tangle/Aderrasi-Chromatic_Abyss_The_Other_Side_",
    "/Waveform/Wire_Flat_Double/Geiss-Electric_Storm_Half-Digital_2_Fiesta_Mix_",
    "/Waveform/Wire_Mirror/Stahlregen_and_Geiss_+_Idiot24-7_+_Illusion_+_Zylot-Twist_Hue_Shaded_Mirror_2",
    "/Geometric/Wire_Spiral/Zylot-Spiral_Hypnotic_Phat_Double_Spiral_Mix_v2",
    "/Waveform/Wire_Tangle/goody_+_shadowharlequin-red_+_blue-chase-megatrip-geiss-aurora_2_v22-2222_v2-shader_fixed_",
    "/Dancer/Lasers/suksma-recognize_flavors_of_resin",
    "/Waveform/Wire_Flat_Double/MegalomaGreg-Ambitions_Flexi_s_mix_12_growth_remix_13_sun_burn_",
    "/Waveform/Wire_Flat_Double/MegalomaGreg-Ambitions_Flexi_s_mix_14_candy_land-Isosceles_edit",
    "/Waveform/Wire_Tunnel/A_MilkKing_Recreation_FT_Martin-Violet_Flash_ft_AdamFX_n_Goody-Belly_Dancer_nz+",
    "/Dancer/Blobby/suksma-anti-glare_dimension_lens_optics_coating",
    "/Dancer/Comet_Mirror/EoS_+_Phat-chasers_11_sentinel_C_poltergeist_mix_response_daemon_NEOhm_s_Blue_Ray_Calm_Tower_ReMix_nz+c5",
    "/Dancer/Glowsticks/Tripgnosis-Neon_Danse",
    "/Dancer/Glowsticks/Tripgnosis-Neon_Danse_friends,_never_reference_the_past",
    "/Dancer/Glowsticks_Mirror/LuxXx-Universe_Garbage_Disposal_3",
    "/Dancer/Lasers/Halfbreak-Time_Machine_is_Runtime_Error",
    "/Waveform/Wire_Spirograph/Fumbling_Foo_and_Flexi,_Martin,_Orb-Star_Forge_v11a",
    "/Waveform/Wire_Rising/372",
    "/Dancer/Glowsticks/EoS_+_Geiss-glowsticks_v2_03_music_shifter_edit_b_water_mix_",
    "/Dancer/Shapes/suksma-dash_head_gainst_elemetaries_aemborael_aeurael_xpectre_nz+",
    "/Dancer/Wake/widest_swing_please_don_t_exclude_me_from_your_metatronic_monogamaniacal_mbo_mbun_ad_mbigre_vawe",
    "/Drawing/Explosions_Mirror/fiShbRaiN-witchcraft_metropolish_remix-test-tillex-dickhead_crumbresum"
  ]
}

**Comment by nzoschke** [comment]
Here are the steps to add these as "official" tags / vibes...

```bash
# check out repo
git clone https://github.com/nzoschke/vizlab-presets.git
cd vizlab-presets
git checkout -b hacienda
touch Tags/hacienda.json

# paste presets in `hacienda.json`
# add `hacienda` to Tags/index.json

git add .
git commit -m 'new tag'
git push origin hacienda
```
